Cool/urls.py
from re import template
from django.urls import path
from . import views
from Cool.views import ( BibleStudyMemberCreateView, GroupsView,
MemberDetailView,
MemberListView, 
BibleStudyMemberUpdateView,
MemberDeleteView,
CourseView,
CourseListView,
MyList,
events_View,
detail_view_for_each_group, groupings_side_view, revert_bs_leader)
app_name="Cool"
urlpatterns=[

    path("events/",events_View, name="events"),
    path('groups/', GroupsView.as_view(),name="all-groups",),
    path('groups/print', GroupsView.as_view(template_name="Cool/print_view.html"),name="print-view",),
    path("groups/<str:group_name>/",detail_view_for_each_group,name="group-detail-view"),

    #The course class view used for the about view, uses the template defined 
    #within the class
    path('about/', CourseView.as_view(),),
    #path('', MyList.as_view(),),
    #path('', CourseListView.as_view(),),

    #The same course class used for the detail view with anothr template 
   # path("<int:id>/", CourseView.as_view(template_name="the_member_detail.html"),),

    #path('create/', CourseCreateView.as_view(),name="member-create"),
    #path('<int:id>/update/', CourseCreateView.as_view(),name="member-create"),
    path('create/', BibleStudyMemberCreateView.as_view(),name="member-create"),
   # path("<int:my_id>/",dynamic_lookup_view),
   # path("",member_list_view,name="list_view"),
    
    path('', MemberListView.as_view(),name="member-list"),  
    #path("",revert_bs_leader,name="revert-view"),
    path('<int:id>/', MemberDetailView.as_view(),name="member-detail"),
    path('<int:id>/update/', BibleStudyMemberUpdateView.as_view(),name="member-update"),
    path('<int:id>/delete/', MemberDeleteView.as_view(),name="member-delete"),

    #Groupings
    path("groupings",groupings_side_view,name="groupings"),
    path('groupings/groups', GroupsView.as_view(),name="groups-groupings",),
]

Uploads/urls.py
from django.urls import path
from  .views import upload_excel_view,learn_javascript

app_name="excel-uploads"
urlpatterns = [
    path("groupingse/upload",upload_excel_view,name='exceluploads'),
    path("java/",learn_javascript,name='java')

    
]

Cool/models.py
from cgitb import handler
from enum import unique
from pickle import TRUE
from django.db import models
from django.urls import reverse

class Reporter(models.Model):
    full_name=models.CharField(max_length=70)

    def __str__(self):
        return self.full_name



class Article(models.Model):
    pub_date=models.DateField()
    headline=models.CharField(max_length=200)
    content=models.TextField()
    reporter=models.ForeignKey(Reporter,on_delete=models.CASCADE)
    
    #This is used to determine the property chosen to describe the class
    def __str__(self):
        return self.headline

# Create your models here.

GENDER_CHOICES=[
    ('F','F'),
    ('M',"M")
]
class The_member(models.Model):
    year_of_study=models.IntegerField()
    gender=models.CharField(max_length=6,choices=GENDER_CHOICES)
    leader_status =models.BooleanField(default=False)
    #leader_pre_status =models.BooleanField(default=False,null=True)

  #  def __str__(self):
  #      return str(self)

    def get_absolute_url(self):
      return reverse("Cool:member-detail",kwargs={"":self.id})  


#BibleStudy Members
class BStudyMember(models.Model):
    first_name=models.CharField(max_length=50)
    middle_name=models.CharField(max_length=50)
    sir_name=models.CharField(max_length=50)
    level=models.IntegerField()
    gender=models.CharField(max_length=1,choices=GENDER_CHOICES)
    leader_status =models.BooleanField(default=False)
    phone_number=models.CharField(max_length=10,unique = True)



    def get_absolute_url(self):
        return reverse("Cool:member-detail",kwargs={"id":self.id})  
    def __str__(self):
        return f"{self.first_name} {self.middle_name} {self.sir_name}"


class Groups_BackUp(models.Model):
    name = models.CharField(max_length=10)
    info = models.CharField(max_length=1000)
    def __str__(self):
        return str(self.name)

Cool/forms.py
from xml.dom import ValidationErr
from django import forms
from django.utils.safestring import  mark_safe
from .models import The_member,BStudyMember

class Bible_SleaderForm(forms.Form):
    set_bs_leader=forms.BooleanField(label="",widget=forms.CheckboxInput(attrs={"class":"choose"}))


class InputForm(forms.Form):
    group_size=forms.IntegerField(initial=6,max_value=2)

class MemberForm(forms.ModelForm):
    class Meta:
        model=The_member
        fields=[
             "year_of_study",
             "gender",
            "leader_status",
        ]
        
        widgets={
            "year_of_study":forms.TimeInput(attrs={"class":"hello"})
        }
        labels={
            "year_of_study":""
        }


    #Clean the fields 
    # make sure that a field has a specific word

    def clean_gender(self,*args,**kwargs):
        gender=self.cleaned_data.get('gender')
        print(gender)
        return gender

    def clean_year_of_study(self,*args, **kwargs):
        year_of_study=self.cleaned_data.get('year_of_study')
      
        if year_of_study!=None:
            if year_of_study > 6 or year_of_study < 1:
                raise forms.ValidationError('This is not a valid level!')
            return year_of_study
        else:
            raise ValidationErr("Please fill the year of study field")


# Horizontal renderer
#class HorizontalRadioRenderer(forms.RadioSelect.renderer):
#    def render(self):
#        return mark_safe(u'\n'.join([u'%sn'% w for w in self]))
class BibleStudyMemberRegisterForm(forms.ModelForm):
    class Meta:
        model=BStudyMember
        fields=[
             "level",
             "gender",
            "leader_status",
            "first_name",
            "middle_name",
            "sir_name",
            "phone_number"
        ]

        widgets={
            "level":forms.NumberInput(attrs={"class":"input-field","placeholder":"year of study"}),
            #"gender":forms.RadioSelect(attrs={"class":"input-field"}),
           # "leader_status":forms.CheckboxInput(attrs={"class":"input-field","placeholder":"Want to be a bs leader?"}),
            "first_name":forms.TextInput(attrs={"class":"input-field","placeholder":"first name"}),
            "middle_name":forms.TextInput(attrs={"class":"input-field","placeholder":"middle name"}),
            "sir_name":forms.TextInput(attrs={"class":"input-field","placeholder":"sir name"}),
            "phone_number":forms.TextInput(attrs={"class":"input-field","placeholder":"Phone number"})

        }
        

        labels={
            
            "first_name":"",
            "middle_name":"",
            "level":"",
            "sir_name":"",
            "phone_number":"",
            "leader_status":"Want to be BS leader? "
        }
    def clean_level(self,*args, **kwargs):
         level=self.cleaned_data.get('level')
         if level!=None:
             if level > 6 or level < 1:
                 print(level)
                 raise forms.ValidationError('This is not a valid level!')
             return level
         else:
             raise ValidationErr(f"Please fill the year of study field")

Cool/views.py
from cgitb import lookup
from functools import wraps
import math
import sys
from itertools import permutations
import random
from operator import ge
from pickletools import int4
from secrets import choice
from tokenize import group
from types import new_class
from unittest import result
from urllib import request, response
from django.db import IntegrityError
from django.shortcuts import get_object_or_404, render,get_list_or_404
from django.http import HttpResponse,Http404
from typing import Counter

from django.urls import is_valid_path,reverse

from Cool.data import Events
from .models import Article, BStudyMember, Groups_BackUp,The_member
from .forms import BibleStudyMemberRegisterForm, InputForm,MemberForm,Bible_SleaderForm
from django.views.generic import (
    TemplateView,
    ListView,
    CreateView,
    UpdateView,
    DeleteView,
    DetailView,
    View
    )
TemplateView.as_view(extra_context={
    "name":"Good Luck"
})



def capture_error(f):
    def  wrapper(*args, **kwargs):
        try:
            return f(*args,**kwargs)
        except:
            return HttpResponse(print("Oops!", sys.exc_info()[0], "occurred."))
    return wrapper

@capture_error
def events_View(request):
         if request.method == "POST":
             Events.__setitem__ (Events["latest"]+1,{
            "date":request.POST['date'],
            "time":request.POST["time"]
              })
             Events['latest']+=1
             context={
                'events':Events
              }
             print(Events)
             return render(request,"Cool/events.html",context)
         return render(request,"Cool/events.html")
 














#generate numbers
def name_generator():
    # The six names to combine
    names=["Markos","Wycliff","Lennox","Geoffrey","Gregory","Mark","James","Ochieng","Kizito","Ziro","Amrose","Beja","Anderson","Michael","Ryan","Budi","Jakes","Amos","Nyale","Raphael","Benson","Janji","Gongolo","Kahati","Kanyoe"]
    rand=random.randint(0,2000)
    full_name=list(permutations(names,3))[rand]
    full_name=(" ".join(full_name))
    return full_name

#generate phone_number
def phone_gen():
    phone=[0,1,2,3,4,5,6,7,8,9]
    rand=random.randint(0,2000)
    phone=list(permutations(phone,8))[rand]
    phone=[str(i) for i in phone]
    phone="".join(phone)
    return phone
def data():
    queryset=BStudyMember.objects.all()
    #if already migrated then dont
    bs_query=BStudyMember.objects.all()
    unlock = 0
    s=0
    Total_members={}
    print(queryset)
    for i in queryset:
        print(i.phone_number)
        full_name=name_generator().split(" ")
        Total_members.__setitem__(str(s),{'year':i.level,'gender':i.gender,'bs_leader':i.leader_status,'id':s,"name":i.first_name +"  "+i.middle_name+"  "+i.sir_name,"sir_name":i.sir_name,'phone':i.phone_number})
        # if len(bs_query)==0 and unlock==1  :

        #      BStudyMember.objects.create(
        #          first_name=full_name[2],
        #          middle_name=full_name[0],
        #          sir_name=full_name[1],
        #          level=i.year_of_study,
        #          gender=i.gender,
        #          leader_status =i.leader_status,
        #          phone_number="07"+str(phone_gen())
        #        )
        s+=1
    return Total_members


Total_members=data()
members_per_group=int(10)
total_groups=math.ceil(len(data())/members_per_group)


#create the groups.
groups={}
for i in range(total_groups):
    groups.__setitem__('group'+str(i),{})



#get the least presented class
def least_class(group,remains):
    group=Counter(group)
    classes=[]
    available=Counter({})
    for item in group:
        classes.append(group[item]['year'])
    for j in [1,2,3,4,5]:
        if j in classes:
            continue
        classes.append(j)
    ratios=Counter(classes).most_common()
    for instance in remains:
            available.__setitem__(remains[instance]['year'],instance)
    i=len(ratios)-1
    #check if there is a class missing
   # print("ratios",ratios)
    smallest_class=[]
    while(i>0):
        if ratios[i][0] in available:
            smallest_class.append(ratios[i][0])
            smallest_class.append(available[ratios[i][0]])
            break
        i-=1

    return smallest_class

    #The logic for the grouping
#groups['default']={1:{"gender":"F",'year':3},2:{"gender":"M",'year':1},3:{"gender":"F",'year':2},4:{"gender":"F",'year':5}}
next_gender=None
Total_members_list=[x for x in Total_members]
pending_items=None
#print(Total_members)
class_ratio=[]
gender_ratio=[]
def check_gender_balance(g,h):
    g=Counter(g)
    h=Counter(h)
    m=f=False
    if h['gender']=='M':
        m=True
    else:
        f=True
    m_c=f_c=0
    for i in g:
        if g[i]['gender']=='M':
            m_c+=1
        else:
            f_c+=1
    if m==True and (m_c-f_c)<=0:
        return True
    elif f==True and (f_c-m_c)<=0:
        return True
    return False
for i in groups:
    each_group=groups[i]
    if len(each_group)==0:
        for item in Total_members:
            if item in Total_members_list:
                 each_group.__setitem__(int(item),Total_members[(item)])
                 Total_members_list.remove(item)
                 break
       
    for member_id in Total_members:
        #Strike gender balance
        next_gender=Counter(([each_group[item]['gender'] for item in each_group])).most_common()
        gender_ratio=next_gender
        #check the most dominant gender
        if len(next_gender)==2:
             if next_gender[0][1] - next_gender[1][1] <= 1:
                 next_gender=next_gender[1][0]
             else:
                 next_gender=next_gender[0][1]
        else:
            if next_gender=="M":
                next_gender="F"
            else:
                next_gender='M'
       #Strike class or year balance i.e  each year to be well distributed
       #get the maximum number of members in a group per class
        max_per_class=-(-members_per_group//5)
     #   print(max_per_class)
        next_class=Counter(([each_group[item]['year'] for item in each_group])).most_common()
        class_ratio=next_class
        class_size=sum([size_of_each_tuple[1] for size_of_each_tuple in next_class])
       # print(class_size)
       # print(next_class)
       # print("member_id",member_id)
       #print(Total_members[member_id]['gender'] )
       #print(next_class[0][1])
        if  member_id  in Total_members_list and class_size<members_per_group and check_gender_balance(each_group,Total_members[member_id]) and next_class[-1][1]<max_per_class:
           each_group.__setitem__(member_id,Total_members[member_id])
           Total_members_list.remove(member_id)
           #print("Hello")



#print(Total_members_list)
#get the remains
remains={}
for key in Total_members_list:
    remains.__setitem__(key,Total_members[key])

#add back all the remainders to the groups
Total_members_list=[x for x in remains]
item=None
try:
   
    for group in groups:
         each_group=groups[group]
         gender=Counter([remains[x]['gender'] for x in remains]).most_common() # M =2, F=7
         while(len(each_group)<members_per_group and len(least_class(each_group,remains))==2): # M =2, F=7
             item=least_class(each_group,remains)[1]
             each_group.__setitem__(item,remains[item])
             remains.__delitem__(item)
except IndexError:
    def er404():
        return Http404("Error occured !")
    er404()
track=len(remains)
for each_group in groups: #group 23 len =5
    each_group=groups[each_group]
    for member in remains:# remains 1
        if (len(each_group)<members_per_group and track>0): # track 11
            if remains[member]:#member
                each_group.__setitem__(member,remains[member])
                remains[member]={}
                track-=1
            



   # continue
    



#for i in groups :
#    each_group=groups[i]
#    next_class=Counter(([each_group[item]['year'] for item in each_group])).most_common()
#    next_gender=Counter(([each_group[item]['gender'] for item in each_group])).most_common()
#    print(i,len(groups[i]),[next_class,next_gender])   
#    for j in groups[i]:
#        print("                ",groups[i][j])

all_data=[]
for i in groups:
    track=0
    class_ratio=[]
    ratio_gender=[]
    intersted_bs_leaders=0
    for j in groups[i]:
        mydict=groups[i][j]
        mydict['group_name']=i
        ratio_gender.append(mydict['gender'])
        class_ratio.append(mydict['year'])
        if mydict['bs_leader'] == True:
            intersted_bs_leaders+=1
        if track==len(groups[i])-1:
            mydict['gender_ratio']=Counter(ratio_gender).most_common()
            mydict['class_ratio']=Counter(class_ratio).most_common()
            mydict['int_leaders']=intersted_bs_leaders
            #get data from back ups
            back_up = Groups_BackUp.objects.all()
            if groups[i] in back_up:
                 mydict['backed_up']=99
        all_data.append(mydict)
        
        track+=1


"""
#get the least gender
def gender_ratio(group):
    group=Counter(group)
    classes=[]
    for item in group:
        classes.append(group[item]['gender'])
    ratio=Counter(classes).most_common()
    return ratio

def check_gender_balance(g,h):
    g=Counter(g)
    h=Counter(h)
    m=f=False
    if h['gender']=='M':
        m=True
    else:
        f=True
    m_c=f_c=0
    for i in g:
        if g[i]['gender']=='M':
            m_c+=1
        else:
            f_c+=1
    if m==True and (m_c-f_c)<=0:
        return True
    elif f==True and (f_c-m_c)<=0:
        return True
    return False

b=[]

def exists(b,k):
    for i in b:
        if k==(i):
            return 1
    return 0

def my_Groups(Total_members,groups,y,b):
   for i in d:
       g=d[i]
       for j in data():
            m=data()[j]
            if len(g)<y-1 and check_gender_balance(g,m):
                max_pop = -(-y//4)
               # print(max_pop)

Cool/templates/Cool/about.html
<html>
    <head>
    </head>
    <body>
        <h1>
            Hello my people this is me.
        </h1>
        <form>
            {{object}}
        </form>
    </body>
    </html>

Cool/templates/Cool/base.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<title>MCCU</title>
<style>
body {margin:0;font-family:Arial;
   background-color: #e5e5f7;
            opacity: 1;
            background-image: radial-gradient(#434cf9 0.65px, #e5e5f7 0.65px);
            background-size: 13px 13px;
        }

.topnav {
  overflow: hidden;
  background-color: #333;
}

.topnav a {
  float: left;
  display: block;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
}

.active {
  background-color: #080808;
  color: white;
}

.topnav .icon {
  display: none;
}

.dropdown {
  float: left;
  overflow: hidden;
}

.dropdown .dropbtn {
  font-size: 17px;    
  border: none;
  outline: none;
  color: white;
  padding: 14px 16px;
  background-color: inherit;
  font-family: inherit;
  margin: 0;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f9f9f9;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

.dropdown-content a {
  float: none;
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
  text-align: left;
}

.topnav a:hover, .dropdown:hover .dropbtn {
  background-color: #555;
  color: white;
}

.dropdown-content a:hover {
  background-color: #ddd;
  color: black;
}

.dropdown:hover .dropdown-content {
  display: block;
}

@media screen and (max-width: 600px) {
  .topnav a:not(:first-child), .dropdown .dropbtn {
    display: none;
  }
  .topnav a.icon {
    float: right;
    display: block;
  }
}

@media screen and (max-width: 600px) {
  .topnav.responsive {position: relative;}
  .topnav.responsive .icon {
    position: absolute;
    right: 0;
    top: 0;
  }
  .topnav.responsive a {
    float: none;
    display: block;
    text-align: left;
  }
  .topnav.responsive .dropdown {float: none;}
  .topnav.responsive .dropdown-content {position: relative;}
  .topnav.responsive .dropdown .dropbtn {
    display: block;
    width: 100%;
    text-align: left;
  }
}
</style>
</head>
<body>

<div class="topnav" id="myTopnav">
  <a href="#home" class="active">MCCU</a>
  <a href="{% url 'Cool:groupings' %}">Grouping</a>
  <a href="{% url 'Cool:member-list' %}">List</a>
  <div class="dropdown">
    <button class="dropbtn">Other  
      <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-content">
      <a href="{% url 'Cool:print-view'%}">Print Data</a>
      <a href="#">Upload</a>
    
    </div>
  </div> 
  <a href="javascript:void(0);" style="font-size:15px;" class="icon" onclick="myFunction()">&#9776;</a>
</div>



<main>
  {% block content%}
  {% endblock%}
</main>

<script>
function myFunction() {
  var x = document.getElementById("myTopnav");
  if (x.className === "topnav") {
    x.className += " responsive";
  } else {
    x.className = "topnav";
  }
}
</script>

</body>
</html>

Cool/templates/Cool/events.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        main{
            margin:10px 30px;
        }
        .event-form{
            width:80%;
            height: 700px;
            display:flex;
            justify-content:center;
            align-items:center;
            flex-direction: column;

        }
    </style>
</head>
<body>
    <main>
        {{events}}
        {% for  i in events %}
            <h1>event {{i}}</h1>
            <p>{{j}}</p>
            <p>{{j}}</p>
            <p type="date"></p>
        {% endfor %}

        <form class="event-form" method="post" action="{% url 'Cool:events' %}">
            {% csrf_token %}
            <input name="name" placeholder="Name" type="text">
            <input name="date" placeholder="date" type="date">
            <input name="time" placeholder="time" type="number">
            <button type="submit">Submit</button>
        </form>
    </main>
</body>
</html>

Cool/templates/Cool/grouping-side.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Grouping</title>
    <style>

        
        *{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            font-family: sans-serif;
        }
        
        body{
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            background-color: #434750;
        }
        
        ul{
            position: relative;
            transform: skewY(-15deg);
        }
        ul li{
            position: relative;
            list-style: none;
            width: 200px;
            background: #3e3f46;
            padding: 15px;
            z-index: var(--i);
        }
        ul li:hover{
            background: #33a3ee;
            transform: translateX(50px);
        }
        ul li::before{
            content: "";
            position: absolute;
            width: 40px;
            top: 0;
            left: -40px;
            height: 100%;
            background: #3e3f46;
            transform-origin: right;
            transform: skewY(45deg);
            transition: 0.5s;
            
        }
        ul li:hover::before{
            background:#2982b9;
        }
        ul li::after{
            content: "";
            position: absolute;
            background: #3e3f46;
            width: 100%;
            height: 40px;
            top: -40px;
            left: 0;
            transform-origin: bottom;
            transform: skewX(45deg);
            transition: 0.5s;
            
        
        }
        ul li:hover::after{
            background:#2982b9;
        }
        ul li a{
            text-decoration: none;
            color: #999;
            display: block;
            text-transform: uppercase;
            letter-spacing: 0.05em;
            transition: 0.5s;
        }
        ul li a:hover{
            color: #fff;
        }
        ul li:last-child::after{
            box-shadow: -120px 120px 20px rgba(0,0,0,0.25);
        }

        /* Share */

        
        html,body{
            display: grid;
            background:#edf7fa;
        }
        
        .wrapper{
            width: 100%;
            height: 50vh;
            display: flex;
        
            justify-content: center;
            align-items: center;
        
        }
        .toggle{
            width: 50px;
            height: 50px;
            background:#c70039;
            border-radius: 50%;
            cursor: pointer;
            position: relative;
        }
        
        .toggle::before{
            content: "\f1e0";
            width: 100%;
            height: 100%;
            font-family: "Font Awesome 5 Free";
            position: absolute;
            color: white;
            line-height: 50px;
            font-size:50px;
            font-weight: 900;
            text-align: center;
        
        }
        .share{
            position: relative;
        }
        .share ol{
            position: absolute;
            width: 50px;
            height: 50px;
        }
        .share ol li{
            position: absolute;
            width: 50px;
            height: 50px;
            display: flex;
            justify-content: center;
            align-items: center;
            border-radius: 50%;
            transition: all .4s;
        
        }
        .share ol li a{
            color: white;
        }
        .share.active .toggle::before{
            content: "\f00d";
            font-size: 2rem;
        
        }
        
        .share.active ol li:nth-child(1){
            background:#0e76a8;
            transition-delay: .2s;
            transform: translateX(60px);
        }
        
        
        .share.active ol li:nth-child(2){
            background:#3b5998;
            transition-delay: .2s;
            transform: translateX(-60px);
        }
        
        
        .share.active ol li:nth-child(3){
            background:#128c7e;
            transition-delay: .2s;
            transform: translateY(-60px);
        }
        
        
        .share.active ol li:nth-child(4){
            background:#1da1f2;
            transition-delay: .2s;
            transform: translateY(60px);
        }
        
    </style>
    <link rel="stylesheet" href="../static/CSS/3d-menu-bar.css" />
  </head>
  <body>
   
 
    <div class="wrapper">
        <ul>
            <li id="nav3d" style="--i: 5;"><a href="{% url 'Cool:groups-groupings'%}"> Groups</a></li>
            <li id="nav3d" style="--i: 4;"><a href="{% url 'Cool:print-view'%}"> Print groups</a></li>
            <li id="nav3d" style="--i: 3;"><a href="{% url 'excel-uploads:exceluploads'%}">Upload</a></li>
            <li id="nav3d" style="--i: 2;"><a href="{% url 'Cool:member-create'%}">Register</a></li>
            <li id="nav3d" style="--i: 1;"><a href="#"> <div class="toggle"></div></a></li>
          
          </ul>
        <div class="share">
          <!-- <li>
            <a href="#"><i class="fab fa-linkedin"></i></a>
          </li>
          <li>
            <a href="#"><i class="fab fa-whatsapp"></i></a>
          </li>
          <li>
            <a href="#"><i class="fab fa-twitter"></i></a>
          </li>
          <li>
            <a href="#"><i class="fab fa-facebook"></i></a>
          </li> -->
          <ol>
            <li>
              <a href="#"></a> <i class="fa fa-university" aria-hidden="true"></i>
            </li>
            <li>
              <a href="#"></a> <i class="fa fa-gift" aria-hidden="true"></i>
            </li>
            <li>
              <a href="#"></a> <i class="fa fa-glass" aria-hidden="true"></i>
            </li>
            <li>
              <a href="#"></a>
              <i class="fa fa-eye-slash" aria-hidden="true"></i>
            </li>
          </ol>
         
        </div>
      </div>
      <script>
        const toggle = document.querySelector(".toggle");
        toggle.addEventListener("click", () => {
          const sharebtn = document.querySelector(".share");
          sharebtn.classList.toggle("active");
        });
      </script>
  </body>
</html>

Cool/templates/Cool/print_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MCCU</title>
    <style>
        .groups{
            width: 100%;
            height:100%;
            display:flex;
            align-items:center;
            justify-content:center;
            position:relative;
            flex-wrap: wrap;
            background:linear-gradient(to right, rgb(53, 52, 52),rgb(139, 131, 131),rgb(139, 131, 131),rgb(139, 131, 131),rgb(72, 69, 69))
        }
        .card{
            width: calc(80%);
            position:relative;
            left: calc(10%);
            height:calc(70%);
        }
        .card li{
            list-style: none;
            color:#111;
            font-size: 12px;
            font-weight: 1000;
        }
        .card a{
            text-decoration: none;
            color:#111;
            font-size: 12px;
            font-weight: 1000;
           
        }
        button{
            background: transparent;
            border:none;
        }
       .inner{
        width: calc(60%);
       
       }
       @media(min-width:650px){
        .card a{
            font-size: 15px;
           
        }
       }
    </style>
</head>
<body>
    <div class="groups">
        {% regroup groups by group_name as bible_study_list %}
        {% for group_name,data in bible_study_list %}
        <ul class="card"  id="{{group_name}}">
                <li class="profile">
                    <h3><a href="{% url 'Cool:group-detail-view' group_name %}">{{group_name|upper}}</a></h3>
                </li>

                   <ul class="inner">

                       {% for member in data %}
                           <li class="inner-row" >
             
                   
                                <span >{{forloop.counter}}. 

                               </span>
                             <button> <a href="{% url 'Cool:member-detail' member.id|add:250 %}"> <span >{{member.name|upper}}</span> <span>{{"-"}}   {{member.phone}}</span></a></button>
                           </li>
                        
                           <li class="inner-row"> {% if forloop.counter == data|length %} 
                 
                            <ul>
                                   <div class="content">
                                       <p> <span>
                                           Gender-ratio  
                                       </span>  {{member.gender_ratio}}</p>
                                        <p> <span>Class Ratio</span> {{member.class_ratio}}</p>
                                       </div>
                            </ul>
                           {% endif  %} </li>
                {% endfor%}
                    
                       </ul>
               
                    </ul>
               {% endfor %}
    </div>
</body>
</html>

Cool/templates/Cool/the_member_delete.html
    {% extends 'Cool/base.html' %}
    {% block content %}
    <form action="." method="POST">
        {% csrf_token %}
      <h1>Do you want to delete the post "{{ object }}" ?</h1>
      <p><input type="submit" value="Yes"></p><a href="../">Cancel</a>
    </form>
       
{% endblock %}
    